Webpage_title = input("Enter the webpage title:")
title_name = input("Enter the title_name:")
header = input("Enter the header:")
sub_header = input("Enter the sub header:")
p1 = input("Enter the paragraph1:")
p2 = input("Enter the paragraph2:")
print(Webpage_title)
print("<html>")
print("<head>")
print("<title>")
print(title_name)
print("</title>")
print("</head>")
print("<body>")
print("<h1>")
print(header)
print("</h1>")
print("<h2>")
print(sub_header)
print("</h2>")
print("<p1>")
print(p1)
print("</p1>")
print("<p2>")
print(p2)
print("</p2>")
print("</body>")
print("</html>")
